spring:
  datasource:
    url: jdbc:mysql://localhost:3307/weathermap
    username: root
    password: hehe2003
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:

